export * from './setPullToRefresh'; // 0
export * from './setWaitCursor'; // 1
export * from './selectTapp'; // 2
export * from './openImage'; // 4
export * from './setCaptionButton'; // 5
export * from './openUrlInBrowser'; // 9
export * from './setBackButton'; // 10
export * from './getGeoLocation'; // 14
export * from './openVideo'; // 15
export * as dialog from './dialogs'; // 16/50/51/30/103
export * from './getGlobalData'; // 18
export * from './vibrate'; // 19
export * from './navigateBack'; // 20
export * from './uploadImage'; // 21
export * from './saveAppointment'; // 29
export * from './openUrl'; // 31
export * from './createQRCode'; // 33
export * from './scanQRCode'; // 34
export * from './getBeaconHistory'; // 36
export * from './setNfcCallback'; // 37/38
export * from './getLocationBeacons'; // 39
export * from './getBeaconMonitoringStatus'; // 46
export * from './addToWallet'; // 47
export * from './login'; // 54/56
export * from './refreshAccessToken'; // 55
export * from './openChaynsId'; // 58
export * from './createTappShortcut'; // 59
export * from './setOnActivateCallback'; // 60
export * from './showFinetradingQRCode'; // 61
export * from './closeUrl'; // 62
export * from './setAccessTokenChange'; // 66
export * from './appendUrlParameter'; // 67
export * from './addErrorListener'; // 68
export * from './setSubTapp'; // 69/70
export * from './setBurgerBadge'; // 71
export * from './setFloatingButton'; // 72
export * as storage from './storage'; // 73/74
export * from './setNetworkChangeCallback'; // 76
export * from './setHeight'; // 77
export * from './getWindowMetrics'; // 78
export * from './share'; // 79/80
export * from './scrollToY'; // 81
export * from './setSpeechToText'; // 82
export * from './setTextToSpeech'; // 83
export * from './updateNavigation'; // 84
export * as search from './search'; // 85/86/87
export * from './setAdminSwitchCallback'; // 88
export * from './setTitleImage'; // 89
export * as passKit from './passKit'; // 90/91
export * from './updateChaynsId'; // 92
export * from './setNfcDetection'; // 93
export * from './setDisplayTimeout'; // 94
export * from './setKioskTapp'; // 95
export * from './setScreenOrientation'; // 96
export * from './playSound'; // 98
export * from './webviewOptions'; // 99/100
export * from './setTemporaryDesignSettings'; // 101
export * from './addScrollListener'; // 102
export * from './registerWatchdog'; // 106
export * from './updateTapp'; // 107
export * from './showSnackBar'; // 109
export * from './uploadFile'; // 110
export * from './sendEventToTopFrame'; // 112
export * from './setWebsiteTitle'; // 114
export * from './setOverlay'; // 116
export * from './setInteractionIdentification'; // 117
export * from './getSavedIntercomChats'; // 127
export * from './setIntercomChatData'; // 128
export * from '../closeWindow'; // 129
export * from './uploadCloudImage'; // Not a real call

